// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpUk8FtW2PII8ANjCgeX3qRK4NFAN6SOs',
    appId: '1:484014128041:web:47024f20ed93f58846a2b8',
    messagingSenderId: '484014128041',
    projectId: 'flutter-firebase-example-add5f',
    authDomain: 'flutter-firebase-example-add5f.firebaseapp.com',
    storageBucket: 'flutter-firebase-example-add5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZfNC9IE45l_0weVNWBX7NP2itjSwv4Q',
    appId: '1:484014128041:android:78f9d14e0bbd8fd146a2b8',
    messagingSenderId: '484014128041',
    projectId: 'flutter-firebase-example-add5f',
    storageBucket: 'flutter-firebase-example-add5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUHcHPBWs6-ywWrse1O5rR4k2Xbf9czDY',
    appId: '1:484014128041:ios:272d35f2c8c2dacd46a2b8',
    messagingSenderId: '484014128041',
    projectId: 'flutter-firebase-example-add5f',
    storageBucket: 'flutter-firebase-example-add5f.appspot.com',
    iosClientId: '484014128041-2ua01d8br9e74htd2d8gvlkg6be09dd3.apps.googleusercontent.com',
    iosBundleId: 'ramazanyerlikaya.flutterFirebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUHcHPBWs6-ywWrse1O5rR4k2Xbf9czDY',
    appId: '1:484014128041:ios:272d35f2c8c2dacd46a2b8',
    messagingSenderId: '484014128041',
    projectId: 'flutter-firebase-example-add5f',
    storageBucket: 'flutter-firebase-example-add5f.appspot.com',
    iosClientId: '484014128041-2ua01d8br9e74htd2d8gvlkg6be09dd3.apps.googleusercontent.com',
    iosBundleId: 'ramazanyerlikaya.flutterFirebaseExample',
  );
}
